apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-challenge-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fc-challenge
  template:
    metadata:
      labels:
        app: fc-challenge
    spec:
      containers:
        - name: fc-challenge
          image: adrianlara/fc-challenge:v1.3
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: fc-challenge-secrets
                  key: secret-key-base
