kind: Service
apiVersion: v1
metadata:
  name: fc-challenge-service
spec:
  selector:
    app: fc-challenge
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 3000
      nodePort: 30001
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-challenge-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fc-challenge
  template:
    metadata:
      labels:
        app: fc-challenge
    spec:
      containers:
        - name: fc-challenge
          image: adrianlara/fc-challenge:v1.0
          ports:
            - containerPort: 3000
