apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-challenge-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fc-challenge
  template:
    metadata:
      labels:
        app: fc-challenge
    spec:
      containers:
        - name: fc-challenge
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fc-challenge-deployment-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: fc-challenge-deployment
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  targetCPUUtilizationPercentage: 50
