apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fc-challenge-deployment-scaler
  annotations:
   "helm.sh/hook": post-install
spec:
  scaleTargetRef:
    kind: Deployment
    name: fc-challenge-deployment
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  targetCPUUtilizationPercentage: 50
