kind: Service
apiVersion: v1
metadata:
  name: fc-challenge-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: fc-challenge
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 3000
      nodePort: 30001
  type: LoadBalancer
